import {useState} from 'react';
import API,{message} from '../axios';
export default function ShoppingAssistant(){
 const [question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function ask(e){e.preventDefault();setBusy(true);setError('');setAnswer('');try{const {data}=await API.post('/assistant/ask',{question:question.trim()});setAnswer(data.answer);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="section narrow"><div className="eyebrow">CATALOG HELP</div><h1>Shopping assistant</h1><p className="muted">Ask about products in the current catalog. Suggestions are generated by AI; check product details before ordering.</p>
 <form className="form" onSubmit={ask}><label htmlFor="shopping-question">What are you looking for?</label><textarea id="shopping-question" rows="4" maxLength="300" required placeholder="Suggest a gift under ₹2,000" value={question} onChange={e=>setQuestion(e.target.value)}/><button className="button" disabled={busy||!question.trim()}>{busy?'Finding suggestions…':'Ask assistant'}</button></form>
 {error&&<p className="notice error" role="alert">{error}</p>}{answer&&<div className="summary" aria-live="polite"><h2>Suggestion</h2><p className="assistant-answer">{answer}</p></div>}</section>;
}
